#ifndef LAYOUT_H
#define LAYOUT_H

const char *layout[] = { "Reserved",
                         "Esc",
                         "1",
                         "2",
                         "3",
                         "4",
                         "5",
                         "6",
                         "7",
                         "8",
                         "9",
                         "0",
                         "-",
                         "=",
                         "Backspace",
                         "Tab",
                         "q",
                         "w",
                         "e",
                         "r",
                         "t",
                         "y",
                         "u",
                         "i",
                         "o",
                         "p",
                         "[",
                         "]",
                         "Enter",
                         "Left Ctrl",
                         "a",
                         "s",
                         "d",
                         "f",
                         "g",
                         "h",
                         "j",
                         "k",
                         "l",
                         ";",
                         "'",
                         "`",
                         "Left Shift",
                         "\\",
                         "z",
                         "x",
                         "c",
                         "v",
                         "b",
                         "n",
                         "m",
                         ",",
                         ".",
                         "/",
                         "Right Shift",
                         "Keypad *",
                         "Left Alt",
                         "Space",
                         "Caps Lock",
                         "F1",
                         "F2",
                         "F3",
                         "F4",
                         "F5",
                         "F6",
                         "F7",
                         "F8",
                         "F9",
                         "F10",
                         "Num Lock",
                         "Scroll Lock",
                         "Keypad 7 \\ Home",
                         "Keypad 8 \\ Up",
                         "Keypad 9 \\ PgUp",
                         "Keypad -",
                         "Keypad 4 \\ Left",
                         "Keypad 5",
                         "Keypad 6 \\ Right",
                         "Keypad +",
                         "Keypad 1 \\ End",
                         "Keypad 2 \\ Down",
                         "Keypad 3 \\ PgDn",
                         "Keypad 0 \\ Ins",
                         "Keypad Dot \\ Delete",
                         "",
                         "Unknown",
                         "<",
                         "F11",
                         "F12" };

#endif
